runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /
  static_files: build/index.html
  upload: build/index.html
- url: /
  static_dir: build
skip_files:

# - ^(.*/)?.*/assets/.*$
# - ^(.*/)?.*/build/.*$
# - ^(.*/)?.*/test/.*$
# - ^(.*/)?.*/templates/.*$
- ^(.*/)?.*/node_modules/.*$

# - ^(assets/.*)
# - ^(build/.*)
# - ^(test/.*)
# - ^(templates/.*)
- ^(node_modules/.*)

- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.DS_Store$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$